// Regenerate src/viewer-assets.ts from viewer/*.
// The compiled single-file binary cannot read viewer/ from disk
// (import.meta.url points into the bundle), so the server falls back to these
// embedded copies. Run after any viewer/ change: `pnpm embed`.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = dirname(dirname(fileURLToPath(import.meta.url)));
const viewerDir = join(pkg, 'viewer');
const out = join(pkg, 'src', 'viewer-assets.ts');

const files = readdirSync(viewerDir).filter((f) => !f.startsWith('.')).sort();
const entries = files.map((f) => {
  const text = readFileSync(join(viewerDir, f), 'utf-8');
  return `  ${JSON.stringify(f)}: ${JSON.stringify(text)},`;
});

writeFileSync(
  out,
  [
    '// GENERATED by scripts/embed-viewer.mjs — do not edit by hand.',
    '// Fallback static assets for the compiled binary (no viewer/ on disk).',
    '',
    'export const viewerAssets: Record<string, string> = {',
    ...entries,
    '};',
    '',
  ].join('\n'),
  'utf-8',
);
console.log(`embedded ${files.length} files → src/viewer-assets.ts`);
